spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: bookadmin
    password: bookadmin
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate

  liquibase:
    user: bookadmin
    password: bookadmin


